name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Execute source file to html
      run: php -f source.php > index.html

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: August Yip
        author_email: augustyip@gmail.com
        message: 'Auto update index.html by github workflow'
        add: 'index.html'

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
